DROP TABLE PROSJEKVRIJEDNOSTIBRZINA;
DROP TABLE BRZINEPROSJEK;
DROP TABLE BRZINEINFO;

DROP TABLE PROSJEKVRIJEDNOSTISVJETLOST;
DROP TABLE SVJETLOSTPROSJEK;
DROP TABLE SVJETLOSTINFO;

DROP TABLE PROSJEKVRIJEDNOSTITOPLINE;
DROP TABLE TOPLINEINFO;
DROP TABLE TOPLINEPROSJEK;

DROP TABLE AKTIVNI_SENZORI_PO_GRUPI;
DROP TABLE SVI_SENZORI_SA_VRSTOM;
DROP TABLE SVI_SENZORI;
DROP TABLE BROJI_UPITE_VRSTA;

DROP STREAM SENZORI_SVJETLOST;
DROP STREAM SENZORI_BRZINE;
DROP STREAM SENZORI_TOPLINE;
DROP STREAM SENZORI;
