CREATE OR REPLACE STREAM SENZORI (ID_SENZORA STRING, VRSTA_SENZORA STRING, VRIJEDNOST INTEGER, VRIJEME STRING) WITH (KAFKA_TOPIC='senzor', KEY_FORMAT='KAFKA', PARTITIONS=3, TIMESTAMP='vrijeme', TIMESTAMP_FORMAT='HH:mm:ss', VALUE_FORMAT='JSON');
CREATE OR REPLACE STREAM SENZORI_TOPLINE AS SELECT * FROM SENZORI WHERE (VRSTA_SENZORA = 'topline') EMIT CHANGES;
CREATE OR REPLACE STREAM SENZORI_BRZINE AS SELECT * FROM SENZORI WHERE (VRSTA_SENZORA = 'brzina') EMIT CHANGES;
CREATE OR REPLACE STREAM SENZORI_SVJETLOST AS SELECT * FROM SENZORI WHERE (VRSTA_SENZORA = 'svjetlost') EMIT CHANGES;


CREATE OR REPLACE TABLE SVI_SENZORI AS SELECT
  SENZORI.ID_SENZORA ID_SENZORA,
  LATEST_BY_OFFSET(SENZORI.VRIJEDNOST) ZADNJA_VRIJEDNOST,
  LATEST_BY_OFFSET(SENZORI.VRIJEME) VRIJEME
FROM SENZORI SENZORI
GROUP BY SENZORI.ID_SENZORA
EMIT CHANGES;


CREATE OR REPLACE TABLE BROJI_UPITE_VRSTA AS SELECT
  SENZORI.VRSTA_SENZORA VRSTA_SENZORA,
  COUNT(*) COUNT
FROM SENZORI SENZORI
GROUP BY SENZORI.VRSTA_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE SVI_SENZORI_SA_VRSTOM AS SELECT
  SENZORI.ID_SENZORA ID_SENZORA,
  LATEST_BY_OFFSET(SENZORI.VRIJEDNOST) ZADNJA_VRIJEDNOST,
  LATEST_BY_OFFSET(SENZORI.VRSTA_SENZORA) VRSTA
FROM SENZORI SENZORI
GROUP BY SENZORI.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE AKTIVNI_SENZORI_PO_GRUPI AS SELECT
  SVI_SENZORI_SA_VRSTOM.VRSTA VRSTA,
  COLLECT_LIST(SVI_SENZORI_SA_VRSTOM.ID_SENZORA) SENZORI,
  COUNT(*) COUNT
FROM SVI_SENZORI_SA_VRSTOM SVI_SENZORI_SA_VRSTOM
WHERE (SVI_SENZORI_SA_VRSTOM.ZADNJA_VRIJEDNOST > 0)
GROUP BY SVI_SENZORI_SA_VRSTOM.VRSTA
EMIT CHANGES;


CREATE OR REPLACE TABLE BRZINEINFO AS SELECT
  SENZORI_BRZINE.ID_SENZORA ID_SENZORA,
  LATEST_BY_OFFSET(SENZORI_BRZINE.VRIJEDNOST, 5) VRIJEDNOST,
  LATEST_BY_OFFSET(SENZORI_BRZINE.VRIJEME, 5) VRIJEME
FROM SENZORI_BRZINE SENZORI_BRZINE
GROUP BY SENZORI_BRZINE.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE BRZINEPROSJEK AS SELECT
  SENZORI_BRZINE.ID_SENZORA ID_SENZORA,
  AVG(SENZORI_BRZINE.VRIJEDNOST) PROSJEK_PODATKA
FROM SENZORI_BRZINE SENZORI_BRZINE
GROUP BY SENZORI_BRZINE.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE TOPLINEPROSJEK AS SELECT
  SENZORI_TOPLINE.ID_SENZORA ID_SENZORA,
  AVG(SENZORI_TOPLINE.VRIJEDNOST) PROSJEK_PODATKA
FROM SENZORI_TOPLINE SENZORI_TOPLINE
GROUP BY SENZORI_TOPLINE.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE TOPLINEINFO AS SELECT
  SENZORI_TOPLINE.ID_SENZORA ID_SENZORA,
  LATEST_BY_OFFSET(SENZORI_TOPLINE.VRIJEDNOST, 5) VRIJEDNOST,
  LATEST_BY_OFFSET(SENZORI_TOPLINE.VRIJEME, 5) VRIJEME
FROM SENZORI_TOPLINE SENZORI_TOPLINE
GROUP BY SENZORI_TOPLINE.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE SVJETLOSTINFO AS SELECT
  SENZORI_SVJETLOST.ID_SENZORA ID_SENZORA,
  LATEST_BY_OFFSET(SENZORI_SVJETLOST.VRIJEDNOST, 5) VRIJEDNOST,
  LATEST_BY_OFFSET(SENZORI_SVJETLOST.VRIJEME, 5) VRIJEME
FROM SENZORI_SVJETLOST SENZORI_SVJETLOST
GROUP BY SENZORI_SVJETLOST.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE SVJETLOSTPROSJEK AS SELECT
  SENZORI_SVJETLOST.ID_SENZORA ID_SENZORA,
  AVG(SENZORI_SVJETLOST.VRIJEDNOST) PROSJEK_PODATKA
FROM SENZORI_SVJETLOST SENZORI_SVJETLOST
GROUP BY SENZORI_SVJETLOST.ID_SENZORA
EMIT CHANGES;

CREATE OR REPLACE TABLE  prosjekVrijednostiTopline AS
SELECT VR.ID_SENZORA AS ID, VR.VRIJEDNOST AS VRIJEDNOST, PR.PROSJEK_PODATKA AS PROSJEK
FROM TOPLINEINFO VR
INNER JOIN TOPLINEPROSJEK PR ON VR.ID_SENZORA = PR.ID_SENZORA;

CREATE OR REPLACE TABLE  prosjekVrijednostiSvjetlost AS
SELECT VR.ID_SENZORA AS ID, VR.VRIJEDNOST AS VRIJEDNOST, PR.PROSJEK_PODATKA AS PROSJEK
FROM SVJETLOSTINFO VR
INNER JOIN SVJETLOSTPROSJEK PR ON VR.ID_SENZORA = PR.ID_SENZORA;

CREATE OR REPLACE TABLE prosjekVrijednostiBrzina AS SELECT VR.ID_SENZORA AS ID, VR.VRIJEDNOST AS VRIJEDNOST, PR.PROSJEK_PODATKA AS PROSJEK
FROM BRZINEINFO VR
INNER JOIN BRZINEPROSJEK PR ON VR.ID_SENZORA = PR.ID_SENZORA;




INSERT INTO SENZORI VALUES('k1','brzina',40,'12:33:44');
INSERT INTO SENZORI VALUES('k1','brzina',58,'12:33:48');
INSERT INTO SENZORI VALUES('k1','brzina',46,'12:33:49');
INSERT INTO SENZORI VALUES('k1','brzina',42,'12:33:51');
INSERT INTO SENZORI VALUES('k1','brzina',55,'12:33:52');
INSERT INTO SENZORI VALUES('k1','brzina',39,'12:34:01');

INSERT INTO SENZORI VALUES('t2','topline',82,'14:21:22');
INSERT INTO SENZORI VALUES('t2','topline',89,'14:21:50');
INSERT INTO SENZORI VALUES('t2','topline',91,'14:22:13');
INSERT INTO SENZORI VALUES('t2','topline',94,'14:22:19');
INSERT INTO SENZORI VALUES('t2','topline',99,'14:22:25');
INSERT INTO SENZORI VALUES('t2','topline',67,'14:22:30');

INSERT INTO SENZORI VALUES('s3','svjetlost',4020,'13:20:21');
INSERT INTO SENZORI VALUES('s3','svjetlost',3950,'13:20:31');
INSERT INTO SENZORI VALUES('s3','svjetlost',4150,'13:20:41');
INSERT INTO SENZORI VALUES('s3','svjetlost',5000,'13:20:51');
INSERT INTO SENZORI VALUES('s3','svjetlost',5000,'13:20:51');
